### ISSUE TITLE
'auto' type issue

### ISSUE THREAD

**Issue by joelnn** [SaschaWitt/ips4o#3]
I believe at https://github.com/SaschaWitt/ips4o/blob/master/ips4o/base_case.hpp#L56, `val` should be explicitly typed as `std::iterator_traits<It>::value_type`. Otherwise, depending on what `std::iterator_traits<It>::reference` is, `val` could end up being a `reference`.

I am using ips4o with a custom 'zipped' iterator formed from two underlying iterators, to simultaneously sort an array while tracking the corresponding indices for the original array order. My `std::iterator_traits<It>::reference` type is not literally a reference type as in `double&`, it's more like `std::tuple<IterA, IterB>`, so I ran into this.

**Comment by SaschaWitt** [comment]
Thanks for your report. I just changed this, and I believe this is the only instance that needs to be changed for this to work. If you still have issues, please feel free to post about them again.
