### ISSUE TITLE
nth element selection

### ISSUE THREAD

**Issue by cfiutak1** [SaschaWitt/ips4o#6]
Has any work been done on creating a linear-time selection algorithm based on this? If so, are there any performance comparisons between that and std::nth_element?

**Comment by MichaelAxtmann** [comment]
Hello cfiutak1,

No, there has not been done any work in this direction. It should be rather simple to convert ips4o into a selection algorithm though. In the sequential case, you only recurse on the important bucket and track the number of elements in the buckets with smaller elements. In the parallel case, you may also change the assignment of threads to tasks. Overall, you choose a different base case algorithm.

Saying that, I assume that this variant outperforms std::nth_element.

Best,
Michael
